services:
  - type: web
    name: quizapp-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://your-db-host:3306/your-db-name?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: your-db-username
      - key: SPRING_DATASOURCE_PASSWORD
        value: your-db-password
